### ISSUE TITLE
Theme doesn't work unless you create variables

### ISSUE THREAD

**Issue by daviddarnes** [danoxide/Anaconda#1]
[Line 60 in partials/header.php](https://github.com/danoxide/Anaconda/blob/master/partial/header.php#L60) requests if variable `jumbotron_title` and `jumbotron_text` are empty or not. I suggest adding a check if the variables exist as well.

I understand it is part of the design, but themes for Anchor CMS need to work out of the box. Thanks for creating themes for @AnchorCMS!! :star2:

**Comment by danoxide** [comment]
@daviddarnes, thanks! When I find free time, I'll fix it ;)

**Comment by danoxide** [comment]
@daviddarnes, I tested it and everything is okay - there aren't any issues when variable exists or not.

**Comment by daviddarnes** [comment]
@danoxide which version did you test the theme with?

**Comment by danoxide** [comment]
@daviddarnes latest version from the master branch (v0.9).

**Comment by daviddarnes** [comment]
@danoxide cool, as long as it works out of the box then awesome!
